info:
  component: Hystrix Dashboard
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

spring:
  application:
    name: hystrix-server
 
server:
  port: 8763
  
logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'
  path: ./logs
  file: ./logs/hystrix.log    
  
  
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  fetchRegistry: false   
  

instance:
  #Virtual host name by which the clients identifies this service
  virtualHostName: ${spring.application.name}